In [1]:
#Import necessary functions
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import datetime


from datetime import datetime as dt

%matplotlib inline

In [2]:
#Import the dataset
df = pd.read_csv('data/Final_Motor_Vehicle_Collisions_QuBr_2018-2023_Class.csv')

#Initial look into dataset
df.head()

,CRASH DATE TIME,COLLISION_ID,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,CONTRIBUTING CATEGORY V1,CONTRIBUTING CATEGORY V2,SEASON,TIME OF DAY,IS RUSH HOUR
0,2018-01-01 00:00:00,3820945,BROOKLYN,11234,40.628770,-73.91825,1,0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,Sedan,Bike,Moving Violation,Moving Violation,Winter,Late Night,False
1,2018-01-01 00:48:00,3821048,BROOKLYN,11203,40.639260,-73.93777,0,0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working,Station Wagon/Sport Utility Vehicle,Sedan,Road Conditions,Road Conditions,Winter,Late Night,False
2,2018-01-01 01:30:00,3819375,QUEENS,11101,40.740913,-73.95226,0,0,Following Too Closely,Following Too Closely,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Moving Violation,Moving Violation,Winter,Late Night,False
3,2018-01-01 01:55:00,3821031,BROOKLYN,11226,40.652412,-73.95396,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,Sedan,Sedan,Driver Error,Driver Error,Winter,Late Night,False
4,2018-01-01 02:29:00,3820976,QUEENS,11418,40.694690,-73.83505,2,0,Other Vehicular,Following Too Closely,Station Wagon/Sport Utility Vehicle,Sedan,Third-Party (Vehicular),Moving Violation,Winter,Early Morning,False

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30701 entries, 0 to 30700
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CRASH DATE TIME                30701 non-null  object
 1   COLLISION_ID                   30701 non-null  int64
 2   BOROUGH                        30701 non-null  object
 3   ZIP CODE                       30701 non-null  int64
 4   LATITUDE                       30701 non-null  float64
 5   LONGITUDE                      30701 non-null  float64
 6   NUMBER OF PERSONS INJURED      30701 non-null  int64
 7   NUMBER OF PERSONS KILLED       30701 non-null  int64
 8   CONTRIBUTING FACTOR VEHICLE 1  30701 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 2  30701 non-null  object
 10  VEHICLE TYPE CODE 1            30701 non-null  object
 11  VEHICLE TYPE CODE 2            30701 non-null  object
 12  CONTRIBUTING CATEGORY V1       30701 non-null  object
 13  CONTRIBUTING CATEGORY V2       30701 non-null  object
 14  SEASON                         30701 non-null  object
 15  TIME OF DAY                    30701 non-null  object
 16  IS RUSH HOUR                   30701 non-null  bool
dtypes: bool(1), float64(2), int64(4), object(10)
memory usage: 3.8+ MB

## Feature Importance

In [8]:
df['VEHICLE TYPE CODE 1'].unique()

array(['Sedan', 'Station Wagon/Sport Utility Vehicle', 'Bus', 'Dump',
       'Taxi', 'Box Truck', 'Bike', 'Van', 'PK', 'Snow Plow',
       'Tractor Truck Gasoline', 'Pick-up Truck', 'Garbage or Refuse',
       'Stake or Rack', 'FORKL', 'Carry All', 'FREIG',
       'Tractor Truck Diesel', 'Ambulance', 'Sweep', 'Motorcycle',
       'Convertible', 'Flat Bed', 'SEMI-', 'Motorscooter', 'STAK',
       'Tanker', 'Bulk Agriculture', 'Flat Rack', 'Armored Truck',
       'Beverage Truck', 'utili', 'Chassis Cab', 'Moped', 'Fire', 'FDNY',
       'Tow Truck / Wrecker', 'TRUCK', 'Concrete Mixer', 'Pallet', 'SELF',
       'TOW T', '15 Pa', 'Refrigerated Van', 'fdny', 'Motorbike',
       'Lift Boom', 'DUMPS', 'MOTOR', 'DUMP', 'ELECT', 'Pedicab', 'scoot',
       'EBIKE', 'Glass Rack', 'Multi-Wheeled Vehicle', 'Tow Truck',
       '3-Door', 'SCOOT', 'TRAIL', 'School Bus', 'Firet', 'Vanette',
       '3 WHE', 'truck', 'Comme', 'Box t', 'AMBUL', 'trail', 'Ambul',
       'tract', 'BUCKE', 'SEGWA', 'Deliv', 'Livestock Rack', 'COMME',
       'Hopper', 'SCHOO', 'firet', 'E-BIK', 'deliv', 'TRLR', 'subn',
       'Scoot', 'tow', 'AMBU', 'FIRE', 'Tow T', 'E-Bik', 'E-Sco', 'CAT.',
       'LIMO', 'TANKE', 'Van Camper', 'schoo', 'Box T', '4 dr sedan',
       'FLAT', 'TRAILER', '2 dr sedan', 'MOPD', 'E-Bike', 'van', 'tr',
       'moped', 'FORK LIFT', 'TRL', 'AMBULANCE', 'FDNY FIRE', 'E-Scooter',
       'FIRE TRUCK', 'ambulance', 'F550', 'CATAPILLAR', 'PERM', 'DELV',
       'Government', 'SKID LOADE', 'FDNY TRUCK', 'Open Body', 'Amb',
       'dump', 'MACK', 'AMBULANE', 'AMB', 'Trailer', 'VAN/TRUCK', 'MOPED',
       'usps truck', '994', 'Dump truck', 'Pick wh', 'PC', 'Gas scoote',
       'FORKLIFT', 'STREET SWE', '12 passage', 'Firetruck', 'DUMPTRUCK',
       'e-scooter', 'Lift', 'Scooter', 'FedEx box', 'Truck', 'MTA BUS',
       'USPS Truck'], dtype=object)

In [9]:
df['VEHICLE TYPE CODE 1'].value_counts()

Sedan                                  14379
Station Wagon/Sport Utility Vehicle    11611
Taxi                                     822
Pick-up Truck                            809
Box Truck                                600
                                       ...
COMME                                      1
Livestock Rack                             1
SEGWA                                      1
BUCKE                                      1
USPS Truck                                 1
Name: VEHICLE TYPE CODE 1, Length: 146, dtype: int64

In [ ]:
'Sedan', 
'Station Wagon/Sport Utility Vehicle', 
'Bus', 
'Dump',
'Taxi', 
'Box Truck', 
'Bike', 
'Van', 
'PK', 
'Snow Plow',
'Tractor Truck Gasoline', 
'Pick-up Truck', 
'Garbage or Refuse',
'Stake or Rack', 
'FORKL', 
'Carry All', 
'FREIG',
'Tractor Truck Diesel', 
'Ambulance', 
'Sweep', 
'Motorcycle',
'Convertible', 
'Flat Bed', 
'SEMI-', 
'Motorscooter', 
'STAK',
'Tanker', 
'Bulk Agriculture', 
'Flat Rack', 
'Armored Truck',
'Beverage Truck', 
'utili', 
'Chassis Cab', 
'Moped', 
'Fire', 
'FDNY',
'Tow Truck / Wrecker', 
'TRUCK', 
'Concrete Mixer', 
'Pallet', 
'SELF',
'TOW T', 
'15 Pa', 
'Refrigerated Van', 
'fdny', 
'Motorbike',
'Lift Boom', 
'DUMPS', 
'MOTOR', 
'DUMP', 
'ELECT', 
'Pedicab', 
'scoot',
'EBIKE', 
'Glass Rack', 
'Multi-Wheeled Vehicle', 
'Tow Truck',
'3-Door', 
'SCOOT', 
'TRAIL', 
'School Bus', 
'Firet', 
'Vanette',
'3 WHE', 
'truck', 
'Comme', 
'Box t', 
'AMBUL', 
'trail', 
'Ambul',
'tract', 
'BUCKE', 
'SEGWA', 
'Deliv', 
'Livestock Rack', 
'COMME',
'Hopper', 
'SCHOO', 
'firet', 
'E-BIK', 
'deliv', 
'TRLR', 
'subn',
'Scoot', 
'tow', 
'AMBU', 
'FIRE', 
'Tow T', 
'E-Bik', 
'E-Sco', 
'CAT.',
'LIMO', 
'TANKE', 
'Van Camper', 
'schoo', 
'Box T', 
'4 dr sedan',
'FLAT', 
'TRAILER', 
'2 dr sedan', 
'MOPD', 
'E-Bike', 
'van', 
'tr',
'moped', 
'FORK LIFT', 
'TRL', 
'AMBULANCE', 
'FDNY FIRE', 
'E-Scooter',
'FIRE TRUCK', 
'ambulance', 
'F550', 
'CATAPILLAR', 
'PERM', 
'DELV',
'Government', 
'SKID LOADE', 
'FDNY TRUCK', 
'Open Body', 
'Amb',
'dump', 
'MACK', 
'AMBULANE', 
'AMB', 
'Trailer', 
'VAN/TRUCK', 
'MOPED',
'usps truck', 
'994', 
'Dump truck', 
'Pick wh', 
'PC', 
'Gas scoote',
'FORKLIFT', 
'STREET SWE', 
'12 passage', 
'Firetruck', 
'DUMPTRUCK',
'e-scooter', 
'Lift', 
'Scooter', 
'FedEx box', 
'Truck', 
'MTA BUS',
'USPS Truck'

In [42]:
#Export as a .csv as final cleaned dataset
#df.to_csv('data/Final_Motor_Vehicle_Collisions_QuBr_2018-2023_Class.csv')