In [52]:
#Import necessary functions
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import folium

from datetime import datetime as dt
from sklearn.preprocessing import OneHotEncoder

%matplotlib inline

In [53]:
df = pd.read_csv('data/Final_Motor_Vehicle_Collisions_QuBr_2018-2023_Class.csv')
df.head()

,CRASH DATE TIME,COLLISION_ID,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,CONTRIBUTING CATEGORY V1,CONTRIBUTING CATEGORY V2,SEASON,TIME OF DAY,IS RUSH HOUR
0,2018-01-01 00:00:00,3820945,BROOKLYN,11234,40.628770,-73.91825,1,0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,Sedan,Bike,Moving Violation,Moving Violation,Winter,Late Night,False
1,2018-01-01 00:48:00,3821048,BROOKLYN,11203,40.639260,-73.93777,0,0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working,Station Wagon/Sport Utility Vehicle,Sedan,Road Conditions,Road Conditions,Winter,Late Night,False
2,2018-01-01 01:30:00,3819375,QUEENS,11101,40.740913,-73.95226,0,0,Following Too Closely,Following Too Closely,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Moving Violation,Moving Violation,Winter,Late Night,False
3,2018-01-01 01:55:00,3821031,BROOKLYN,11226,40.652412,-73.95396,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,Sedan,Sedan,Driver Error,Driver Error,Winter,Late Night,False
4,2018-01-01 02:29:00,3820976,QUEENS,11418,40.694690,-73.83505,2,0,Other Vehicular,Following Too Closely,Station Wagon/Sport Utility Vehicle,Sedan,Third-Party (Vehicular),Moving Violation,Winter,Early Morning,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30862 entries, 0 to 30861
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CRASH DATE TIME                30862 non-null  object
 1   COLLISION_ID                   30862 non-null  int64
 2   BOROUGH                        30862 non-null  object
 3   ZIP CODE                       30862 non-null  int64
 4   LATITUDE                       30862 non-null  float64
 5   LONGITUDE                      30862 non-null  float64
 6   NUMBER OF PERSONS INJURED      30862 non-null  int64
 7   NUMBER OF PERSONS KILLED       30862 non-null  int64
 8   CONTRIBUTING FACTOR VEHICLE 1  30862 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 2  30862 non-null  object
 10  VEHICLE TYPE CODE 1            30862 non-null  object
 11  VEHICLE TYPE CODE 2            30862 non-null  object
 12  CONTRIBUTING CATEGORY V1       30862 non-null  object
 13  CONTRIBUTING CATEGORY V2       30862 non-null  object
 14  SEASON                         30862 non-null  object
 15  TIME OF DAY                    30862 non-null  object
 16  IS RUSH HOUR                   30862 non-null  bool
dtypes: bool(1), float64(2), int64(4), object(10)
memory usage: 3.8+ MB

In [6]:
#Change column to datetime datatype
df['CRASH DATE TIME'] = pd.to_datetime(df['CRASH DATE TIME'])

#### Changing DateTime Index

In [7]:
#Set to datetime index
#df.set_index('CRASH DATE TIME', inplace=True)

In [8]:
#Review the contributing factors
df['CONTRIBUTING FACTOR VEHICLE 1'].value_counts(sort=True).head()

Driver Inattention/Distraction    12610
Other Vehicular                    3059
Failure to Yield Right-of-Way      2612
Passing or Lane Usage Improper     1983
Passing Too Closely                1286
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

## Folium Maps

In [34]:
df

,CRASH DATE TIME,COLLISION_ID,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,CONTRIBUTING CATEGORY V1,CONTRIBUTING CATEGORY V2,SEASON,TIME OF DAY,IS RUSH HOUR
0,2018-01-01 00:00:00,3820945,BROOKLYN,11234,40.628770,-73.918250,1,0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,Sedan,Bike,Moving Violation,Moving Violation,Winter,Late Night,False
1,2018-01-01 00:48:00,3821048,BROOKLYN,11203,40.639260,-73.937770,0,0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working,Station Wagon/Sport Utility Vehicle,Sedan,Road Conditions,Road Conditions,Winter,Late Night,False
2,2018-01-01 01:30:00,3819375,QUEENS,11101,40.740913,-73.952260,0,0,Following Too Closely,Following Too Closely,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Moving Violation,Moving Violation,Winter,Late Night,False
3,2018-01-01 01:55:00,3821031,BROOKLYN,11226,40.652412,-73.953960,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,Sedan,Sedan,Driver Error,Driver Error,Winter,Late Night,False
4,2018-01-01 02:29:00,3820976,QUEENS,11418,40.694690,-73.835050,2,0,Other Vehicular,Following Too Closely,Station Wagon/Sport Utility Vehicle,Sedan,Third-Party (Vehicular),Moving Violation,Winter,Early Morning,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30857,2023-01-01 10:15:00,4594589,BROOKLYN,11207,40.678160,-73.897484,0,0,Driver Inattention/Distraction,Driver Inexperience,Sedan,Sedan,Driver Error,Driver Error,Winter,Late Morning,False
30858,2023-01-01 14:53:00,4594583,BROOKLYN,11208,40.660797,-73.871830,2,0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,Station Wagon/Sport Utility Vehicle,Sedan,Moving Violation,Moving Violation,Winter,Afternoon,False
30859,2023-01-01 19:26:00,4594645,QUEENS,11434,40.689915,-73.777900,1,0,Passenger Distraction,Driver Inattention/Distraction,Sedan,Sedan,Other Distractions,Driver Error,Winter,Night,False
30860,2023-01-01 20:45:00,4594571,BROOKLYN,11209,40.622860,-74.025350,5,0,Unsafe Speed,Failure to Yield Right-of-Way,Sedan,Sedan,Moving Violation,Moving Violation,Winter,Night,False
30861,2023-01-01 23:15:00,4594565,QUEENS,11369,40.757430,-73.876230,0,0,Other Vehicular,Other Vehicular,Station Wagon/Sport Utility Vehicle,Sedan,Third-Party (Vehicular),Third-Party (Vehicular),Winter,Night,False

In [54]:
#Create dataset with only Queens collisions
Queens = df[df['BOROUGH'] == 'QUEENS']

#Create dataframe with only relevant coliums to map making
Queens_Collisions = Queens[['LATITUDE', 'LONGITUDE', 'COLLISION_ID']]
Queens_Collisions

        LATITUDE  LONGITUDE  COLLISION_ID
2      40.740913 -73.952260       3819375
4      40.694690 -73.835050       3820976
6      40.739380 -73.920160       3821499
9      40.762420 -73.827520       3820398
11     40.757725 -73.779274       3818806
...          ...        ...           ...
30852  40.703140 -73.767000       4594388
30854  40.766150 -73.919785       4594338
30855  40.713543 -73.812640       4594890
30859  40.689915 -73.777900       4594645
30861  40.757430 -73.876230       4594565

[14944 rows x 3 columns]

In [1]:
#Create a blank map
map = folium.Map(location=[Queens_Collisions.LATITUDE.mean(), Queens_Collisions.LONGITUDE.mean()], zoom_start=14, control_scale=True)

#Create index markers for Queens collisions
for index, location_info in Queens_Collisions.iterrows():
    folium.Marker([location_info["LATITUDE"], location_info["LONGITUDE"]], popup=location_info["COLLISION_ID"]).add_to(map)
    
map

NameError: name 'folium' is not defined