In [1]:
#Import necessary functions
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import datetime


from datetime import datetime as dt

%matplotlib inline

In [2]:
#Import the dataset
df = pd.read_csv('data/Motor_Vehicle_Collisions_QuBr_2018-2023.csv')

#Initial look into dataset
df.head()

,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2018-01-01 00:00:00,BROOKLYN,11230.0,40.62418,-73.97048,0.0,0.0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,3822296,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
1,2018-01-01 00:00:00,BROOKLYN,11234.0,40.62877,-73.91825,1.0,0.0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,NaN,NaN,NaN,3820945,Sedan,Bike,NaN,NaN,NaN
2,2018-01-01 00:00:00,QUEENS,11419.0,40.68297,-73.82824,0.0,0.0,Passing Too Closely,Unspecified,NaN,NaN,NaN,3819067,Sedan,NaN,NaN,NaN,NaN
3,2018-01-01 00:00:00,BROOKLYN,11239.0,40.65306,-73.88202,0.0,0.0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,3820851,Sedan,NaN,NaN,NaN,NaN
4,2018-01-01 00:00:00,BROOKLYN,11230.0,40.62322,-73.96102,0.0,0.0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,3821055,Taxi,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305681 entries, 0 to 305680
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH DATE TIME                305681 non-null  object
 1   BOROUGH                        305681 non-null  object
 2   ZIP CODE                       305578 non-null  float64
 3   LATITUDE                       298746 non-null  float64
 4   LONGITUDE                      298746 non-null  float64
 5   NUMBER OF PERSONS INJURED      305678 non-null  float64
 6   NUMBER OF PERSONS KILLED       305679 non-null  float64
 7   CONTRIBUTING FACTOR VEHICLE 1  304302 non-null  object
 8   CONTRIBUTING FACTOR VEHICLE 2  246228 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 3  23851 non-null   object
 10  CONTRIBUTING FACTOR VEHICLE 4  6190 non-null    object
 11  CONTRIBUTING FACTOR VEHICLE 5  1919 non-null    object
 12  COLLISION_ID                   305681 non-null  int64
 13  VEHICLE TYPE CODE 1            302717 non-null  object
 14  VEHICLE TYPE CODE 2            219631 non-null  object
 15  VEHICLE TYPE CODE 3            22353 non-null   object
 16  VEHICLE TYPE CODE 4            5947 non-null    object
 17  VEHICLE TYPE CODE 5            1858 non-null    object
dtypes: float64(5), int64(1), object(12)
memory usage: 42.0+ MB

## EDA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305681 entries, 0 to 305680
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH DATE TIME                305681 non-null  object
 1   BOROUGH                        305681 non-null  object
 2   ZIP CODE                       305578 non-null  float64
 3   LATITUDE                       298746 non-null  float64
 4   LONGITUDE                      298746 non-null  float64
 5   NUMBER OF PERSONS INJURED      305678 non-null  float64
 6   NUMBER OF PERSONS KILLED       305679 non-null  float64
 7   CONTRIBUTING FACTOR VEHICLE 1  304302 non-null  object
 8   CONTRIBUTING FACTOR VEHICLE 2  246228 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 3  23851 non-null   object
 10  CONTRIBUTING FACTOR VEHICLE 4  6190 non-null    object
 11  CONTRIBUTING FACTOR VEHICLE 5  1919 non-null    object
 12  COLLISION_ID                   305681 non-null  int64
 13  VEHICLE TYPE CODE 1            302717 non-null  object
 14  VEHICLE TYPE CODE 2            219631 non-null  object
 15  VEHICLE TYPE CODE 3            22353 non-null   object
 16  VEHICLE TYPE CODE 4            5947 non-null    object
 17  VEHICLE TYPE CODE 5            1858 non-null    object
dtypes: float64(5), int64(1), object(12)
memory usage: 42.0+ MB

In [5]:
#Shift 'Collision ID' column to first position
first_column = df.pop('COLLISION_ID')
  
# insert column using insert(position,column_name,first_column) function
df.insert(0, 'COLLISION_ID', first_column)

#### Dropping Columns/Values

In [6]:
#drop additional contributing factor vehicle columns
df.drop(['CONTRIBUTING FACTOR VEHICLE 3', 'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5'], axis=1, inplace=True)

#drop additional vehicle type columns
df.drop(['VEHICLE TYPE CODE 1', 'VEHICLE TYPE CODE 2', 'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4', 'VEHICLE TYPE CODE 5'], axis=1, inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305681 entries, 0 to 305680
Data columns (total 10 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   COLLISION_ID                   305681 non-null  int64
 1   CRASH DATE TIME                305681 non-null  object
 2   BOROUGH                        305681 non-null  object
 3   ZIP CODE                       305578 non-null  float64
 4   LATITUDE                       298746 non-null  float64
 5   LONGITUDE                      298746 non-null  float64
 6   NUMBER OF PERSONS INJURED      305678 non-null  float64
 7   NUMBER OF PERSONS KILLED       305679 non-null  float64
 8   CONTRIBUTING FACTOR VEHICLE 1  304302 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 2  246228 non-null  object
dtypes: float64(5), int64(1), object(4)
memory usage: 23.3+ MB

In [8]:
df.head()

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2
0,3822296,2018-01-01 00:00:00,BROOKLYN,11230.0,40.62418,-73.97048,0.0,0.0,Driver Inattention/Distraction,Unspecified
1,3820945,2018-01-01 00:00:00,BROOKLYN,11234.0,40.62877,-73.91825,1.0,0.0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper
2,3819067,2018-01-01 00:00:00,QUEENS,11419.0,40.68297,-73.82824,0.0,0.0,Passing Too Closely,Unspecified
3,3820851,2018-01-01 00:00:00,BROOKLYN,11239.0,40.65306,-73.88202,0.0,0.0,Driver Inattention/Distraction,NaN
4,3821055,2018-01-01 00:00:00,BROOKLYN,11230.0,40.62322,-73.96102,0.0,0.0,Driver Inattention/Distraction,Unspecified

In [9]:
#Drop NaN values from columns of contributing factors
df = df.dropna(subset=['CONTRIBUTING FACTOR VEHICLE 1', 'CONTRIBUTING FACTOR VEHICLE 2'])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 246228 entries, 0 to 305680
Data columns (total 10 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   COLLISION_ID                   246228 non-null  int64
 1   CRASH DATE TIME                246228 non-null  object
 2   BOROUGH                        246228 non-null  object
 3   ZIP CODE                       246143 non-null  float64
 4   LATITUDE                       240685 non-null  float64
 5   LONGITUDE                      240685 non-null  float64
 6   NUMBER OF PERSONS INJURED      246227 non-null  float64
 7   NUMBER OF PERSONS KILLED       246227 non-null  float64
 8   CONTRIBUTING FACTOR VEHICLE 1  246228 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 2  246228 non-null  object
dtypes: float64(5), int64(1), object(4)
memory usage: 20.7+ MB

In [11]:
df.head()

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2
0,3822296,2018-01-01 00:00:00,BROOKLYN,11230.0,40.62418,-73.97048,0.0,0.0,Driver Inattention/Distraction,Unspecified
1,3820945,2018-01-01 00:00:00,BROOKLYN,11234.0,40.62877,-73.91825,1.0,0.0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper
2,3819067,2018-01-01 00:00:00,QUEENS,11419.0,40.68297,-73.82824,0.0,0.0,Passing Too Closely,Unspecified
4,3821055,2018-01-01 00:00:00,BROOKLYN,11230.0,40.62322,-73.96102,0.0,0.0,Driver Inattention/Distraction,Unspecified
5,3818641,2018-01-01 00:05:00,BROOKLYN,11211.0,40.71846,-73.95281,0.0,0.0,Failure to Yield Right-of-Way,Unspecified

In [12]:
#Check for NaN values in injury/death columns
print(df['NUMBER OF PERSONS KILLED'].isnull().sum())
print(df['NUMBER OF PERSONS INJURED'].isnull().sum())

1
1

In [13]:
#Drop NaN values from injury/death columns
df = df.dropna(subset=['NUMBER OF PERSONS INJURED', 'NUMBER OF PERSONS KILLED'])

#Sanity check to verify no more NaN values
print(df['NUMBER OF PERSONS KILLED'].isnull().sum())
print(df['NUMBER OF PERSONS INJURED'].isnull().sum())

0
0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 246226 entries, 0 to 305680
Data columns (total 10 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   COLLISION_ID                   246226 non-null  int64
 1   CRASH DATE TIME                246226 non-null  object
 2   BOROUGH                        246226 non-null  object
 3   ZIP CODE                       246141 non-null  float64
 4   LATITUDE                       240683 non-null  float64
 5   LONGITUDE                      240683 non-null  float64
 6   NUMBER OF PERSONS INJURED      246226 non-null  float64
 7   NUMBER OF PERSONS KILLED       246226 non-null  float64
 8   CONTRIBUTING FACTOR VEHICLE 1  246226 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 2  246226 non-null  object
dtypes: float64(5), int64(1), object(4)
memory usage: 20.7+ MB

In [15]:
#Filter out the collisions with Unspecified contributing factor
df = df[df['CONTRIBUTING FACTOR VEHICLE 1'] != 'Unspecified']
df = df[df['CONTRIBUTING FACTOR VEHICLE 2'] != 'Unspecified']

df

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2
1,3820945,2018-01-01 00:00:00,BROOKLYN,11234.0,40.628770,-73.918250,1.0,0.0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper
12,3821048,2018-01-01 00:48:00,BROOKLYN,11203.0,40.639260,-73.937770,0.0,0.0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working
21,3819375,2018-01-01 01:30:00,QUEENS,11101.0,40.740913,-73.952260,0.0,0.0,Following Too Closely,Following Too Closely
25,3821031,2018-01-01 01:55:00,BROOKLYN,11226.0,40.652412,-73.953960,0.0,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction
31,3820976,2018-01-01 02:29:00,QUEENS,11418.0,40.694690,-73.835050,2.0,0.0,Other Vehicular,Following Too Closely
...,...,...,...,...,...,...,...,...,...,...
305624,4594589,2023-01-01 10:15:00,BROOKLYN,11207.0,40.678160,-73.897484,0.0,0.0,Driver Inattention/Distraction,Driver Inexperience
305644,4594583,2023-01-01 14:53:00,BROOKLYN,11208.0,40.660797,-73.871830,2.0,0.0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way
305666,4594645,2023-01-01 19:26:00,QUEENS,11434.0,40.689915,-73.777900,1.0,0.0,Passenger Distraction,Driver Inattention/Distraction
305670,4594571,2023-01-01 20:45:00,BROOKLYN,11209.0,40.622860,-74.025350,5.0,0.0,Unsafe Speed,Failure to Yield Right-of-Way
305679,4594565,2023-01-01 23:15:00,QUEENS,11369.0,40.757430,-73.876230,0.0,0.0,Other Vehicular,Other Vehicular

In [16]:
#Drop missing values from Latitude and Longitude columns -- ensure we can map
df = df.dropna(subset=['LATITUDE', 'LONGITUDE'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31896 entries, 1 to 305679
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   COLLISION_ID                   31896 non-null  int64
 1   CRASH DATE TIME                31896 non-null  object
 2   BOROUGH                        31896 non-null  object
 3   ZIP CODE                       31890 non-null  float64
 4   LATITUDE                       31896 non-null  float64
 5   LONGITUDE                      31896 non-null  float64
 6   NUMBER OF PERSONS INJURED      31896 non-null  float64
 7   NUMBER OF PERSONS KILLED       31896 non-null  float64
 8   CONTRIBUTING FACTOR VEHICLE 1  31896 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 2  31896 non-null  object
dtypes: float64(5), int64(1), object(4)
memory usage: 2.7+ MB

In [17]:
#Check for any duplicated rows
df.duplicated().value_counts()

False    31896
dtype: int64

### Imputation

In [18]:
#Check rows with missing zip code
df[df['ZIP CODE'].isna()]

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2
4230,3831700,2018-01-18 17:20:00,QUEENS,NaN,40.72010,-73.79038,0.0,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction
18961,3868814,2018-03-24 23:20:00,QUEENS,NaN,40.72010,-73.79038,0.0,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction
24496,3884297,2018-04-18 18:00:00,QUEENS,NaN,40.72010,-73.79038,0.0,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction
108657,4107049,2019-04-01 17:00:00,QUEENS,NaN,40.72010,-73.79038,0.0,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction
269385,4507585,2022-02-22 18:52:00,QUEENS,NaN,40.72013,-73.79038,0.0,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction
284136,4541523,2022-06-27 09:27:00,QUEENS,NaN,40.72013,-73.79038,1.0,0.0,Unsafe Lane Changing,Unsafe Lane Changing

In [19]:
#Impute rows with missing zip code values
df.loc[4230,'ZIP CODE'] = 11432
df.loc[18961,'ZIP CODE'] = 11432
df.loc[24496,'ZIP CODE'] = 11432
df.loc[108657,'ZIP CODE'] = 11432
df.loc[269385,'ZIP CODE'] = 11432
df.loc[284136,'ZIP CODE'] = 11432

In [20]:
#Sanity check to confirm zipcode was imputed for indexed row
df[df.index.isin(['2018-01-18 17:20:00'])]

Empty DataFrame
Columns: [COLLISION_ID, CRASH DATE TIME, BOROUGH, ZIP CODE, LATITUDE, LONGITUDE, NUMBER OF PERSONS INJURED, NUMBER OF PERSONS KILLED, CONTRIBUTING FACTOR VEHICLE 1, CONTRIBUTING FACTOR VEHICLE 2]
Index: []

In [21]:
#Sanity check to confirm zipcode was imputed for indexed row
df.loc[[4230]]

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2
4230,3831700,2018-01-18 17:20:00,QUEENS,11432.0,40.7201,-73.79038,0.0,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction

In [22]:
#Sanity check to confirm there's no more NaN values in Zip Code column
df[df['ZIP CODE'].isna()]

Empty DataFrame
Columns: [COLLISION_ID, CRASH DATE TIME, BOROUGH, ZIP CODE, LATITUDE, LONGITUDE, NUMBER OF PERSONS INJURED, NUMBER OF PERSONS KILLED, CONTRIBUTING FACTOR VEHICLE 1, CONTRIBUTING FACTOR VEHICLE 2]
Index: []

### Feature Engineering

#### Contributing Categories

In [23]:
#Review the contributing factors
df['CONTRIBUTING FACTOR VEHICLE 1'].value_counts(sort=True).head()

Driver Inattention/Distraction    12842
Other Vehicular                    3463
Failure to Yield Right-of-Way      2664
Passing or Lane Usage Improper     2049
Passing Too Closely                1328
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

In [24]:
#Check the unique values of contributing factors for vehicle 1
df['CONTRIBUTING FACTOR VEHICLE 1'].unique()

array(['Failure to Yield Right-of-Way',
       'Traffic Control Device Improper/Non-Working',
       'Following Too Closely', 'Driver Inattention/Distraction',
       'Other Vehicular', 'Driver Inexperience',
       'View Obstructed/Limited', 'Passing or Lane Usage Improper',
       'Backing Unsafely', 'Turning Improperly', 'Unsafe Speed', 'Glare',
       'Passing Too Closely', 'Oversized Vehicle',
       'Aggressive Driving/Road Rage', 'Unsafe Lane Changing',
       'Outside Car Distraction', 'Traffic Control Disregarded',
       'Pavement Slippery', 'Alcohol Involvement',
       'Reaction to Uninvolved Vehicle', 'Driverless/Runaway Vehicle',
       'Obstruction/Debris',
       'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion',
       'Tire Failure/Inadequate', 'Pavement Defective',
       'Lane Marking Improper/Inadequate', 'Headlights Defective',
       'Steering Failure', 'Illnes', 'Passenger Distraction',
       'Failure to Keep Right', 'Brakes Defective', 'Drugs (illegal)',
       'Animals Action', 'Other Lighting Defects',
       'Cell Phone (hand-Held)', 'Vehicle Vandalism',
       'Accelerator Defective', 'Texting', 'Fell Asleep',
       'Tow Hitch Defective', 'Fatigued/Drowsy',
       'Shoulders Defective/Improper', 'Lost Consciousness',
       'Tinted Windows', 'Physical Disability', 'Eating or Drinking',
       'Using On Board Navigation Device'], dtype=object)

In [25]:
#Check the unique values of contributing factors for vehicle 2
df['CONTRIBUTING FACTOR VEHICLE 2'].unique()

array(['Passing or Lane Usage Improper',
       'Traffic Control Device Improper/Non-Working',
       'Following Too Closely', 'Driver Inattention/Distraction',
       'Driver Inexperience', 'Failure to Yield Right-of-Way',
       'Passing Too Closely', 'View Obstructed/Limited',
       'Other Vehicular', 'Backing Unsafely', 'Unsafe Speed',
       'Aggressive Driving/Road Rage', 'Pavement Slippery',
       'Turning Improperly', 'Reaction to Uninvolved Vehicle',
       'Unsafe Lane Changing',
       'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion',
       'Oversized Vehicle', 'Traffic Control Disregarded',
       'Obstruction/Debris', 'Glare', 'Pavement Defective',
       'Outside Car Distraction', 'Tire Failure/Inadequate',
       'Lane Marking Improper/Inadequate', 'Passenger Distraction',
       'Alcohol Involvement', 'Failure to Keep Right', 'Brakes Defective',
       'Illnes', 'Lost Consciousness', 'Fatigued/Drowsy',
       'Driverless/Runaway Vehicle', 'Windshield Inadequate',
       'Cell Phone (hand-Held)', 'Steering Failure', 'Eating or Drinking',
       'Fell Asleep', 'Tinted Windows', 'Animals Action',
       'Physical Disability', 'Other Lighting Defects',
       'Accelerator Defective', 'Vehicle Vandalism',
       'Tow Hitch Defective', 'Other Electronic Device',
       'Prescription Medication', 'Headlights Defective', 'Texting',
       'Drugs (illegal)', 'Listening/Using Headphones',
       'Shoulders Defective/Improper'], dtype=object)

In [26]:
#Create duplicate columns of contributing factor columns for categorizing
df['CONTRIBUTING CATEGORY V1'] = df['CONTRIBUTING FACTOR VEHICLE 1']
df['CONTRIBUTING CATEGORY V2'] = df['CONTRIBUTING FACTOR VEHICLE 2']

/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1117203809.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'] = df['CONTRIBUTING FACTOR VEHICLE 1']
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1117203809.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'] = df['CONTRIBUTING FACTOR VEHICLE 2']

In [27]:
#Replace value with correct spelling of 'Illness'
df['CONTRIBUTING FACTOR VEHICLE 1'].replace('Illnes', 'Illness', inplace=True)
df['CONTRIBUTING FACTOR VEHICLE 2'].replace('Illnes', 'Illness', inplace=True)

/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/418796937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING FACTOR VEHICLE 1'].replace('Illnes', 'Illness', inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/418796937.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING FACTOR VEHICLE 2'].replace('Illnes', 'Illness', inplace=True)

In [28]:
#Replace specific contributing factor to a more generalized category in Contributing Category Vehicle 1
df['CONTRIBUTING CATEGORY V1'].replace(('Driver Inattention/Distraction', 'Driver Inexperience', 'Reaction to Uninvolved Vehicle', 'Aggressive Driving/Road Rage', 'Eating or Drinking'), ('Driver Error'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Tire Failure/Inadequate', 'Headlights Defective', 'Steering Failure', 'Brakes Defective', 'Accelerator Defective', 'Tow Hitch Defective', 'Other Lighting Defects', 'Tinted Windows', 'Vehicle Vandalism'), ('Vehicle Defects'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Failure to Yield Right-of-Way','Passing or Lane Usage Improper','Unsafe Lane Changing','Failure to Keep Right', 'Traffic Control Disregarded','Passing Too Closely', 'Backing Unsafely', 'Unsafe Speed', 'Following Too Closely', 'Turning Improperly'), ('Moving Violation'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Glare', 'Obstruction/Debris', 'View Obstructed/Limited'), ('Environmental Factors'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Cell Phone (hand-Held)', 'Texting', 'Using On Board Navigation Device'), ('Internal Electronics Usage'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Illnes', 'Illness', 'Drugs (illegal)', 'Fell Asleep', 'Fatigued/Drowsy', 'Lost Consciousness', 'Physical Disability', 'Alcohol Involvement'), ('Bodily Impairment'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Traffic Control Device Improper/Non-Working', 'Pavement Slippery', 'Pavement Defective', 'Shoulders Defective/Improper', 'Lane Marking Improper/Inadequate'), ('Road Conditions'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Driverless/Runaway Vehicle', 'Other Vehicular', 'Oversized Vehicle'), ('Third-Party (Vehicular)'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Animals Action', 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion'), ('Third-Party (Non-Vehicular)'), inplace=True)

df['CONTRIBUTING CATEGORY V1'].replace(('Passenger Distraction', 'Outside Car Distraction'), ('Other Distractions'), inplace=True)

#Replace specific contributing factor to a more generalized category in Contributing Category Vehicle 2
df['CONTRIBUTING CATEGORY V2'].replace(('Driver Inattention/Distraction', 'Driver Inexperience', 'Reaction to Uninvolved Vehicle', 'Aggressive Driving/Road Rage', 'Eating or Drinking'), ('Driver Error'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Tire Failure/Inadequate', 'Headlights Defective', 'Steering Failure', 'Brakes Defective', 'Accelerator Defective', 'Tow Hitch Defective', 'Other Lighting Defects', 'Tinted Windows', 'Vehicle Vandalism', 'Windshield Inadequate'), ('Vehicle Defects'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Failure to Yield Right-of-Way','Passing or Lane Usage Improper','Unsafe Lane Changing','Failure to Keep Right', 'Traffic Control Disregarded','Passing Too Closely', 'Backing Unsafely', 'Unsafe Speed', 'Following Too Closely', 'Turning Improperly'), ('Moving Violation'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Glare', 'Obstruction/Debris', 'View Obstructed/Limited'), ('Environmental Factors'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Cell Phone (hand-Held)', 'Texting', 'Using On Board Navigation Device', 'Other Electronic Device', 'Listening/Using Headphones'), ('Internal Electronics Usage'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Illness', 'Drugs (illegal)', 'Fell Asleep', 'Fatigued/Drowsy', 'Lost Consciousness', 'Physical Disability', 'Alcohol Involvement', 'Prescription Medication'), ('Bodily Impairment'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Traffic Control Device Improper/Non-Working', 'Pavement Slippery', 'Pavement Defective', 'Shoulders Defective/Improper', 'Lane Marking Improper/Inadequate'), ('Road Conditions'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Driverless/Runaway Vehicle', 'Other Vehicular', 'Oversized Vehicle'), ('Third-Party (Vehicular)'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Animals Action', 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion'), ('Third-Party (Non-Vehicular)'), inplace=True)

df['CONTRIBUTING CATEGORY V2'].replace(('Passenger Distraction', 'Outside Car Distraction'), ('Other Distractions'), inplace=True)

/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Driver Inattention/Distraction', 'Driver Inexperience', 'Reaction to Uninvolved Vehicle', 'Aggressive Driving/Road Rage', 'Eating or Drinking'), ('Driver Error'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Tire Failure/Inadequate', 'Headlights Defective', 'Steering Failure', 'Brakes Defective', 'Accelerator Defective', 'Tow Hitch Defective', 'Other Lighting Defects', 'Tinted Windows', 'Vehicle Vandalism'), ('Vehicle Defects'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Failure to Yield Right-of-Way','Passing or Lane Usage Improper','Unsafe Lane Changing','Failure to Keep Right', 'Traffic Control Disregarded','Passing Too Closely', 'Backing Unsafely', 'Unsafe Speed', 'Following Too Closely', 'Turning Improperly'), ('Moving Violation'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Glare', 'Obstruction/Debris', 'View Obstructed/Limited'), ('Environmental Factors'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Cell Phone (hand-Held)', 'Texting', 'Using On Board Navigation Device'), ('Internal Electronics Usage'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Illnes', 'Illness', 'Drugs (illegal)', 'Fell Asleep', 'Fatigued/Drowsy', 'Lost Consciousness', 'Physical Disability', 'Alcohol Involvement'), ('Bodily Impairment'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Traffic Control Device Improper/Non-Working', 'Pavement Slippery', 'Pavement Defective', 'Shoulders Defective/Improper', 'Lane Marking Improper/Inadequate'), ('Road Conditions'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Driverless/Runaway Vehicle', 'Other Vehicular', 'Oversized Vehicle'), ('Third-Party (Vehicular)'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Animals Action', 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion'), ('Third-Party (Non-Vehicular)'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V1'].replace(('Passenger Distraction', 'Outside Car Distraction'), ('Other Distractions'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Driver Inattention/Distraction', 'Driver Inexperience', 'Reaction to Uninvolved Vehicle', 'Aggressive Driving/Road Rage', 'Eating or Drinking'), ('Driver Error'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Tire Failure/Inadequate', 'Headlights Defective', 'Steering Failure', 'Brakes Defective', 'Accelerator Defective', 'Tow Hitch Defective', 'Other Lighting Defects', 'Tinted Windows', 'Vehicle Vandalism', 'Windshield Inadequate'), ('Vehicle Defects'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Failure to Yield Right-of-Way','Passing or Lane Usage Improper','Unsafe Lane Changing','Failure to Keep Right', 'Traffic Control Disregarded','Passing Too Closely', 'Backing Unsafely', 'Unsafe Speed', 'Following Too Closely', 'Turning Improperly'), ('Moving Violation'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Glare', 'Obstruction/Debris', 'View Obstructed/Limited'), ('Environmental Factors'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Cell Phone (hand-Held)', 'Texting', 'Using On Board Navigation Device', 'Other Electronic Device', 'Listening/Using Headphones'), ('Internal Electronics Usage'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Illness', 'Drugs (illegal)', 'Fell Asleep', 'Fatigued/Drowsy', 'Lost Consciousness', 'Physical Disability', 'Alcohol Involvement', 'Prescription Medication'), ('Bodily Impairment'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Traffic Control Device Improper/Non-Working', 'Pavement Slippery', 'Pavement Defective', 'Shoulders Defective/Improper', 'Lane Marking Improper/Inadequate'), ('Road Conditions'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Driverless/Runaway Vehicle', 'Other Vehicular', 'Oversized Vehicle'), ('Third-Party (Vehicular)'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Animals Action', 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion'), ('Third-Party (Non-Vehicular)'), inplace=True)
/var/folders/v0/p588qkrd5kb8kdnf_3zrlbm80000gn/T/ipykernel_22690/1919467257.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTRIBUTING CATEGORY V2'].replace(('Passenger Distraction', 'Outside Car Distraction'), ('Other Distractions'), inplace=True)

In [29]:
#Convert columns from float to integers
df = df.astype({'ZIP CODE':'int64', 'NUMBER OF PERSONS INJURED':'int64', 'NUMBER OF PERSONS KILLED':'int64'})

In [30]:
df

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING CATEGORY V1,CONTRIBUTING CATEGORY V2
1,3820945,2018-01-01 00:00:00,BROOKLYN,11234,40.628770,-73.918250,1,0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,Moving Violation,Moving Violation
12,3821048,2018-01-01 00:48:00,BROOKLYN,11203,40.639260,-73.937770,0,0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working,Road Conditions,Road Conditions
21,3819375,2018-01-01 01:30:00,QUEENS,11101,40.740913,-73.952260,0,0,Following Too Closely,Following Too Closely,Moving Violation,Moving Violation
25,3821031,2018-01-01 01:55:00,BROOKLYN,11226,40.652412,-73.953960,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,Driver Error,Driver Error
31,3820976,2018-01-01 02:29:00,QUEENS,11418,40.694690,-73.835050,2,0,Other Vehicular,Following Too Closely,Third-Party (Vehicular),Moving Violation
...,...,...,...,...,...,...,...,...,...,...,...,...
305624,4594589,2023-01-01 10:15:00,BROOKLYN,11207,40.678160,-73.897484,0,0,Driver Inattention/Distraction,Driver Inexperience,Driver Error,Driver Error
305644,4594583,2023-01-01 14:53:00,BROOKLYN,11208,40.660797,-73.871830,2,0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,Moving Violation,Moving Violation
305666,4594645,2023-01-01 19:26:00,QUEENS,11434,40.689915,-73.777900,1,0,Passenger Distraction,Driver Inattention/Distraction,Other Distractions,Driver Error
305670,4594571,2023-01-01 20:45:00,BROOKLYN,11209,40.622860,-74.025350,5,0,Unsafe Speed,Failure to Yield Right-of-Way,Moving Violation,Moving Violation
305679,4594565,2023-01-01 23:15:00,QUEENS,11369,40.757430,-73.876230,0,0,Other Vehicular,Other Vehicular,Third-Party (Vehicular),Third-Party (Vehicular)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31896 entries, 1 to 305679
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   COLLISION_ID                   31896 non-null  int64
 1   CRASH DATE TIME                31896 non-null  object
 2   BOROUGH                        31896 non-null  object
 3   ZIP CODE                       31896 non-null  int64
 4   LATITUDE                       31896 non-null  float64
 5   LONGITUDE                      31896 non-null  float64
 6   NUMBER OF PERSONS INJURED      31896 non-null  int64
 7   NUMBER OF PERSONS KILLED       31896 non-null  int64
 8   CONTRIBUTING FACTOR VEHICLE 1  31896 non-null  object
 9   CONTRIBUTING FACTOR VEHICLE 2  31896 non-null  object
 10  CONTRIBUTING CATEGORY V1       31896 non-null  object
 11  CONTRIBUTING CATEGORY V2       31896 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 4.2+ MB

In [32]:
#Change to datetime datatype
df['CRASH DATE TIME'] = pd.to_datetime(df['CRASH DATE TIME']) #changing to datetime datatype

#### Season

In [33]:
#Create Season column
## Months 3-5 = Spring
## Months 6-8 = Summer
## Months 9-11 = Autumn
## Months 12-2 = Winter

df['SEASON'] = np.where(((df["CRASH DATE TIME"].dt.month >= 3) & (df["CRASH DATE TIME"].dt.month <= 5)), 'Spring',
                          np.where(((df["CRASH DATE TIME"].dt.month >= 6) & (df["CRASH DATE TIME"].dt.month <= 8)), 'Summer',
                                  np.where(((df["CRASH DATE TIME"].dt.month >= 9) & (df["CRASH DATE TIME"].dt.month <= 11)), 'Autumn', 'Winter')))

df['SEASON'].value_counts()

Summer    8420
Autumn    8015
Spring    7763
Winter    7698
Name: SEASON, dtype: int64

In [34]:
df

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING CATEGORY V1,CONTRIBUTING CATEGORY V2,SEASON
1,3820945,2018-01-01 00:00:00,BROOKLYN,11234,40.628770,-73.918250,1,0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,Moving Violation,Moving Violation,Winter
12,3821048,2018-01-01 00:48:00,BROOKLYN,11203,40.639260,-73.937770,0,0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working,Road Conditions,Road Conditions,Winter
21,3819375,2018-01-01 01:30:00,QUEENS,11101,40.740913,-73.952260,0,0,Following Too Closely,Following Too Closely,Moving Violation,Moving Violation,Winter
25,3821031,2018-01-01 01:55:00,BROOKLYN,11226,40.652412,-73.953960,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,Driver Error,Driver Error,Winter
31,3820976,2018-01-01 02:29:00,QUEENS,11418,40.694690,-73.835050,2,0,Other Vehicular,Following Too Closely,Third-Party (Vehicular),Moving Violation,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...
305624,4594589,2023-01-01 10:15:00,BROOKLYN,11207,40.678160,-73.897484,0,0,Driver Inattention/Distraction,Driver Inexperience,Driver Error,Driver Error,Winter
305644,4594583,2023-01-01 14:53:00,BROOKLYN,11208,40.660797,-73.871830,2,0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,Moving Violation,Moving Violation,Winter
305666,4594645,2023-01-01 19:26:00,QUEENS,11434,40.689915,-73.777900,1,0,Passenger Distraction,Driver Inattention/Distraction,Other Distractions,Driver Error,Winter
305670,4594571,2023-01-01 20:45:00,BROOKLYN,11209,40.622860,-74.025350,5,0,Unsafe Speed,Failure to Yield Right-of-Way,Moving Violation,Moving Violation,Winter
305679,4594565,2023-01-01 23:15:00,QUEENS,11369,40.757430,-73.876230,0,0,Other Vehicular,Other Vehicular,Third-Party (Vehicular),Third-Party (Vehicular),Winter

#### Time of Day

In [35]:
#Define the bins
bins=[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 24]

#Custom labels for time of day/hour intervals
labels=['Late Night', 'Early Morning', 'Dawn', 'Early AM', 'Morning', 'Late Morning', 'Early Afternoon', 
        'Afternoon', 'Evening', 'Night']

#Add the bins to the dataframe
df['TIME OF DAY'] = pd.cut(df['CRASH DATE TIME'].dt.hour, bins, labels=labels, right=False)

In [36]:
df

,COLLISION_ID,CRASH DATE TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING CATEGORY V1,CONTRIBUTING CATEGORY V2,SEASON,TIME OF DAY
1,3820945,2018-01-01 00:00:00,BROOKLYN,11234,40.628770,-73.918250,1,0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,Moving Violation,Moving Violation,Winter,Late Night
12,3821048,2018-01-01 00:48:00,BROOKLYN,11203,40.639260,-73.937770,0,0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working,Road Conditions,Road Conditions,Winter,Late Night
21,3819375,2018-01-01 01:30:00,QUEENS,11101,40.740913,-73.952260,0,0,Following Too Closely,Following Too Closely,Moving Violation,Moving Violation,Winter,Late Night
25,3821031,2018-01-01 01:55:00,BROOKLYN,11226,40.652412,-73.953960,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,Driver Error,Driver Error,Winter,Late Night
31,3820976,2018-01-01 02:29:00,QUEENS,11418,40.694690,-73.835050,2,0,Other Vehicular,Following Too Closely,Third-Party (Vehicular),Moving Violation,Winter,Early Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305624,4594589,2023-01-01 10:15:00,BROOKLYN,11207,40.678160,-73.897484,0,0,Driver Inattention/Distraction,Driver Inexperience,Driver Error,Driver Error,Winter,Late Morning
305644,4594583,2023-01-01 14:53:00,BROOKLYN,11208,40.660797,-73.871830,2,0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,Moving Violation,Moving Violation,Winter,Afternoon
305666,4594645,2023-01-01 19:26:00,QUEENS,11434,40.689915,-73.777900,1,0,Passenger Distraction,Driver Inattention/Distraction,Other Distractions,Driver Error,Winter,Night
305670,4594571,2023-01-01 20:45:00,BROOKLYN,11209,40.622860,-74.025350,5,0,Unsafe Speed,Failure to Yield Right-of-Way,Moving Violation,Moving Violation,Winter,Night
305679,4594565,2023-01-01 23:15:00,QUEENS,11369,40.757430,-73.876230,0,0,Other Vehicular,Other Vehicular,Third-Party (Vehicular),Third-Party (Vehicular),Winter,Night

#### Rush Hour

In [37]:
#Change to datetime datatype
df['CRASH DATE TIME'] = pd.to_datetime(df['CRASH DATE TIME']) #changing to datetime datatype

#Set to datetime index
df.set_index('CRASH DATE TIME', inplace=True)

In [38]:
#Create and join dataframes indicating rush hour traffic
rush_hour = pd.concat([df.between_time('6:00', '9:00'), df.between_time('16:00', '19:00')])

#Create new column indicating if rush hour -- return True if index is in rush_hour, False if not
df['IS RUSH HOUR'] = df.index.isin(rush_hour.index)

#Sanity check to confirm there are True/False values
df['IS RUSH HOUR'].value_counts()

False    20956
True     10940
Name: IS RUSH HOUR, dtype: int64

In [39]:
df

,COLLISION_ID,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING CATEGORY V1,CONTRIBUTING CATEGORY V2,SEASON,TIME OF DAY,IS RUSH HOUR
CRASH DATE TIME,,,,,,,,,,,,,,
2018-01-01 00:00:00,3820945,BROOKLYN,11234,40.628770,-73.918250,1,0,Failure to Yield Right-of-Way,Passing or Lane Usage Improper,Moving Violation,Moving Violation,Winter,Late Night,False
2018-01-01 00:48:00,3821048,BROOKLYN,11203,40.639260,-73.937770,0,0,Traffic Control Device Improper/Non-Working,Traffic Control Device Improper/Non-Working,Road Conditions,Road Conditions,Winter,Late Night,False
2018-01-01 01:30:00,3819375,QUEENS,11101,40.740913,-73.952260,0,0,Following Too Closely,Following Too Closely,Moving Violation,Moving Violation,Winter,Late Night,False
2018-01-01 01:55:00,3821031,BROOKLYN,11226,40.652412,-73.953960,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,Driver Error,Driver Error,Winter,Late Night,False
2018-01-01 02:29:00,3820976,QUEENS,11418,40.694690,-73.835050,2,0,Other Vehicular,Following Too Closely,Third-Party (Vehicular),Moving Violation,Winter,Early Morning,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-01 10:15:00,4594589,BROOKLYN,11207,40.678160,-73.897484,0,0,Driver Inattention/Distraction,Driver Inexperience,Driver Error,Driver Error,Winter,Late Morning,False
2023-01-01 14:53:00,4594583,BROOKLYN,11208,40.660797,-73.871830,2,0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,Moving Violation,Moving Violation,Winter,Afternoon,False
2023-01-01 19:26:00,4594645,QUEENS,11434,40.689915,-73.777900,1,0,Passenger Distraction,Driver Inattention/Distraction,Other Distractions,Driver Error,Winter,Night,False
2023-01-01 20:45:00,4594571,BROOKLYN,11209,40.622860,-74.025350,5,0,Unsafe Speed,Failure to Yield Right-of-Way,Moving Violation,Moving Violation,Winter,Night,False
2023-01-01 23:15:00,4594565,QUEENS,11369,40.757430,-73.876230,0,0,Other Vehicular,Other Vehicular,Third-Party (Vehicular),Third-Party (Vehicular),Winter,Night,False

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 31896 entries, 2018-01-01 00:00:00 to 2023-01-01 23:15:00
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   COLLISION_ID                   31896 non-null  int64
 1   BOROUGH                        31896 non-null  object
 2   ZIP CODE                       31896 non-null  int64
 3   LATITUDE                       31896 non-null  float64
 4   LONGITUDE                      31896 non-null  float64
 5   NUMBER OF PERSONS INJURED      31896 non-null  int64
 6   NUMBER OF PERSONS KILLED       31896 non-null  int64
 7   CONTRIBUTING FACTOR VEHICLE 1  31896 non-null  object
 8   CONTRIBUTING FACTOR VEHICLE 2  31896 non-null  object
 9   CONTRIBUTING CATEGORY V1       31896 non-null  object
 10  CONTRIBUTING CATEGORY V2       31896 non-null  object
 11  SEASON                         31896 non-null  object
 12  TIME OF DAY                    31896 non-null  category
 13  IS RUSH HOUR                   31896 non-null  bool
dtypes: bool(1), category(1), float64(2), int64(4), object(6)
memory usage: 3.2+ MB

In [41]:
#Export as a .csv as final cleaned dataset
df.to_csv('data/Final_Motor_Vehicle_Collisions_QuBr_2018-2023.csv')